rm(list = ls())
print ("SETUP Script for the CEFLEX score-modeller tool")
print ("---------------------------------------------------------------------------------")
print ("This script will install the required R packages to run the scoring modeller.")
print ("If asked for a download mirror, please select an appropriate choice to continue.")
print ("---------------------------------------------------------------------------------")
print ("Installing packages for the development environment")
install.packages("languageserver", repos="https://ftp.belnet.be/mirror/CRAN/")
print ("---------------------------------------------------------------------------------")
print ("Installing packages dependencies")
install.packages("officer", repos="https://ftp.belnet.be/mirror/CRAN/")
install.packages("tidyverse", repos="https://ftp.belnet.be/mirror/CRAN/")
install.packages("read_xlsx", repos="https://ftp.belnet.be/mirror/CRAN/")
install.packages("writexl", repos="https://ftp.belnet.be/mirror/CRAN/")
install.packages("splitstackshape", repos="https://ftp.belnet.be/mirror/CRAN/")
install.packages("tools", repos="https://ftp.belnet.be/mirror/CRAN/")